# Generated by Django 2.2.4 on 2021-01-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccr_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
